# Generated by Django 3.2.18 on 2023-03-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content_tokens',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество токенов в сообщении'),
        ),
    ]
