# Generated by Django 3.2.18 on 2023-03-22 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_message_content_tokens'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='BotMessage',
        ),
    ]
