# Generated by Django 3.2.18 on 2023-04-20 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0003_rename_message_botmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmessage',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.chatuser', verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
